# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'
        
    Ethio\Covid19Bundle\:
        resource: '../../src/Ethio/Covid19Bundle/*'
#        resource: '../../src/Ethio/Covid19Bundle/Security/'
        exclude: '../../src/Ethio/Covid19Bundle/**/{Entity,Repository,Tests}'        
    OST\UABundle\:
        resource: '../../src/OST/UABundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/OST/UABundle/**/{Entity,Repository,Tests}'

# Fixtures services
    Ethio\Covid19Bundle\DataFixtures\ORM\:
        resource: '../../src/Ethio/Covid19Bundle/DataFixtures/ORM'
        tags: [doctrine.fixture.orm]
    # add more services, or override services that need manual wiring
    # authentication failure event listener
    ocaua.security.authentication_failure_event_listener:
        class: OST\UABundle\Report\AuthenticationListener
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
 
    # authentication success event listener
    ocaua.security.interactive_login_listener:
        class: OST\UABundle\Report\AuthenticationListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }
            
    ocaua.security.interactive_logoutlistener:
        class: OST\UABundle\Report\AuthenticationListener
   

