<?php

namespace Ethio\Covid19Bundle\Repository;

/**
 * AboutUsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutUsRepository extends \Doctrine\ORM\EntityRepository
{
}
