<?php

namespace Ethio\Covid19Bundle\Repository;

/**
 * VisitorLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorLogRepository extends \Doctrine\ORM\EntityRepository
{
  public function getStat() {
    $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select('v.visitor_username as username, count(v.visitor_username) as Totalcount')
                ->from('Covid19Bundle:VisitorLog', 'v')
                ->groupBy('v.visitor_username')
                ->orderBy('Totalcount', 'DESC')
                ->getQuery();
        
        return $query->getResult();
    }

}
