<?php

namespace OST\UABundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllUsers($organization)
    {
        $fields = array('u.first_name','u.username');
        return $this->createQueryBuilder('u')
            ->select($fields)
            ->join('u.office', 'o')
            ->where('o.organization = :organization')
//            ->andWhere('u.identifier_key = :identifier_key')
            ->setParameter('project', $project)
//            ->setParameter('project', $project)
            ->orderBy('p.id','DESC')
            ->getQuery()
            ->getResult();
    }
}
