group_index:
    path:     /
    defaults: { _controller: "OSTUABundle:Group:index" }
    methods:  [GET, POST]

group_show:
    path:     /{id}/show
    defaults: { _controller: "OSTUABundle:Group:show" }
    methods:  GET

group_new:
    path:     /new
    defaults: { _controller: "OSTUABundle:Group:new" }
    methods:  [GET, POST]

group_edit:
    path:     /{id}/edit
    defaults: { _controller: "OSTUABundle:Group:edit" }
    methods:  [GET, POST]

group_delete:
    path:     /{id}/delete
    defaults: { _controller: "OSTUABundle:Group:delete" }
    methods:  DELETE
