user_index:
    path:     /
    defaults: { _controller: "OSTUABundle:User:index" }
    methods:  [GET, POST]

user_show:
    path:     /{id}/show
    defaults: { _controller: "OSTUABundle:User:show" }
    methods:  GET

user_swich_status:
    path:     /{id}/swich-status
    defaults: { _controller: "OSTUABundle:User:switch" }
    methods:  GET

user_showusr:
    path:     /{id}/showusr
    defaults: { _controller: "OSTUABundle:User:showuser" }
    methods:  GET
    
user_contact_info:
    path:     /{username}/showUserContact
    defaults: { _controller: "OSTUABundle:User:userContactInfo" }


user_new:
    path:     /new
    defaults: { _controller: "OSTUABundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "OSTUABundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "OSTUABundle:User:delete" }
    methods:  DELETE
