Ethio\Covid19Bundle\Entity\RecievedLetter:
  type: entity
  table: recieved_letter
  repositoryClass: Ethio\Covid19Bundle\Repository\RecievedLetterRepository             
  gedmo:
    loggable: true 
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    date:
      type: date
      gedmo:
        timestampable:
          on: update
    ref_number:
      type: string
      length: 255
      unique: true 
    subject:
      type: string
      length: 255
    upload_letter:
      type: string
      length: 10000

  manyToOne:
      organizationnames:
        targetEntity: Ethio\Covid19Bundle\Entity\OrganizationName
        inversedBy: recievedletters
        joinColumn:
            name: organizationname_id
            referencedColumnName: id              
